
version: '3.8'

services:
  appflowy-cloud:
    image: appflowyinc/appflowy_cloud:latest
    container_name: appflowy_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      # --- DATABASE ---
      - APPFLOWY_DATABASE_URL=postgres://flowy:rootflowy@postgres_db:5432/appflowy
      
      # --- REDIS (PERUBAHAN 1: Pake nama container langsung) ---
      - APPFLOWY_REDIS_URL=redis://appflowy_redis:6379
      
      # --- MINIO ---
      - APPFLOWY_S3_ACCESS_KEY=minioadmin
      - APPFLOWY_S3_SECRET_KEY=minioadmin
      - APPFLOWY_S3_BUCKET=appflowy
      - APPFLOWY_S3_REGION=us-east-1
      - APPFLOWY_S3_ENDPOINT=http://minio:9000
      - APPFLOWY_S3_USE_SSL=false
      - APPFLOWY_ACCESS_URL=https://flow.theputras.my.id
      - APPFLOWY_WEB_URL=https://flow.theputras.my.id
      - APPFLOWY_GOTRUE_JWT_SECRET=kdYsZ8mK_Rv4-APxH2ayFco_gIM5_WUrGN0pdbZY2Qo=
    
    networks:
      - psql_net
      - appflowy-net  
    
    depends_on:
      - minio
      - redis

  # --- SERVICE REDIS ---
  redis:
    image: redis:alpine
    container_name: appflowy_redis # <--- Ini Target Kita
    restart: always
    # PERUBAHAN 2: Paksa bind ke semua IP dan matikan save disk (biar cepet & anti error permission)
    command: redis-server --bind 0.0.0.0 --save "" --appendonly no
    networks:
      - appflowy-net

  # --- MINIO ---
  minio:
    image: minio/minio
    container_name: appflowy_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio_data:/data
    ports:
      - "9005:9000"
      - "9006:9001"
    networks:
      - appflowy-net

networks:
  appflowy-net:
    driver: bridge

  psql_net:
    external: true
    name: psql_net
